dashboard:
  states:
  - label: "{{numvalue.value}}"
  actions: []
  panelItems: []
detailView:
- label: "{{i18n.label}}"
  displayType: numberField
  numberField:
    value: numvalue.value
    valueType: number
    command: set
    argumentType: number
automation:
  conditions:
  - label: "{{i18n.label}}"
    displayType: numberField
    numberField:
      value: numvalue.value
      valueType: number
  actions:
  - label: "{{i18n.commands.label}}"
    displayType: numberField
    numberField:
      command: set
      argumentType: number
  - label: "{{i18n.commands.label}}"
    displayType: numberField
    numberField:
      command: add
      argumentType: number
  - label: "{{i18n.commands.label}}"
    displayType: numberField
    numberField:
      command: minus
      argumentType: number
  - label: "{{i18n.commands.label}}"
    displayType: numberField
    numberField:
      command: multiply
      argumentType: number
  - label: "{{i18n.commands.label}}"
    displayType: numberField
    numberField:
      command: divide
      argumentType: number
      minimum: 1